/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AESUtil */

#ifndef _Included_AESUtil
#define _Included_AESUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AESUtil
 * Method:    encrypt
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AESUtil_encrypt
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     AESUtil
 * Method:    decrypt
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AESUtil_decrypt
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
